### ISSUE TITLE
Convert all growables to RICO with one button.

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/Ploppable-RICO-Revisited#25]
Convert all growables to RICO with one button.

**Comment by algernon-A** [comment]
0c01f760cf236e0b19a4f4eb5e0c9f18f48b0ef3 makes this feasible to investigate further.

**Comment by Sipke82** [comment]
And in my thought process the next step be to make all residential level 1 :-)

**Comment by algernon-A** [comment]
With all the updates over the past few years, is this still valid?

**Comment by Sipke82** [comment]
I think this can be closed.
