### ISSUE TITLE
Dump all RICO settings to LocalRICOsettings.xml 

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/Ploppable-RICO-Revisited#26]
Dump all RICO settings to LocalRICOsettings.xml

This would enable easy editing of all buildings using an XML editor.

**Comment by algernon-A** [comment]
Good idea!

**Comment by algernon-A** [comment]
With all the updates over the past few years, is this still valid?

**Comment by Sipke82** [comment]
I think this can be closed.
