### ISSUE TITLE
Add a shortcut button to the rico settings on building tooltip.

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/Ploppable-RICO-Revisited#28]
Would be nice to have a shortcut button on the building tooltip towards the RICO settings. Often it's quite a struggle to find (in the rico settings) the specific building you have just placed.

I mean this tooltip:
https://www.gameplayinside.com/wp-content/uploads/2015/03/cities-skylines-guide-how-residential-zones-work-tooltip-850x479.jpg

(please keep in mind other mods like painter and customize it (which also places buttons there)

**Comment by algernon-A** [comment]
Initial approach is to look at reactivating Customize It integration.

**Comment by algernon-A** [comment]
Fixed by c7e7c505a7d35cd2838bfc3ecd114048ca141ee0
