### ISSUE TITLE
Override CheckZoning on 'growable' assets so they can also be plopped

### ISSUE THREAD

**Issue by algernon-A** [algernon-A/Ploppable-RICO-Revisited#40]

**Comment by Sipke82** [comment]
Is there some reason why people couldn't just use the "Plop the Growables" mod?

**Comment by algernon-A** [comment]
They could, but people are expecting to be able to plop buildings directly from the RICO menu.  Still on the fence on this one; leaving it to Plop the Growables is definitely an option,

**Comment by algernon-A** [comment]
Going to go with this as an optional toggle, but as a low priority.

**Comment by algernon-A** [comment]
Fixed in 849b02257c56dfe7b952530bb1c0e778e71fb71b
