### ISSUE TITLE
Larger PloppableTool panel

### ISSUE THREAD

**Issue by algernon-A** [algernon-A/Ploppable-RICO-Revisited#41]
Possibly in combination with Extended Toolbar mod.

**Comment by Sipke82** [comment]
Well people could use the "resize it" mod.

**Comment by algernon-A** [comment]
Also an option, although many people don't use those and don't want to.  Still on the fence on this one.

**Comment by algernon-A** [comment]
Closing this, as 'Yet Another Toolbar' is doing as good a job (or better) than can be done here, and changing this panel without changing other tool panels introduces multiple issues in any case.
