### ISSUE TITLE
Changing Worker/household count should automatically fill jobs for the different education levels

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/Ploppable-RICO-Revisited#47]
Changing Worker/household count should automatically fill jobs for the different education levels

https://i.imgur.com/WDqPVMS.jpg

**Comment by algernon-A** [comment]
Agreed.  Was working on adding buttons, but you're right - this is a better way.

**Comment by algernon-A** [comment]
Fixed by 1602b97d2b93abfaf766d4a6ba54c6ab7ab4daeb
