### ISSUE TITLE
When opening settings, select current building

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/Ploppable-RICO-Revisited#50]
When settings screen is opened via main UI, it would be nice if it could show the settings for whatever building I had selected in th main UI.

I've often wanted to just quickly open the settings for a building, but when opening Settings via main UI I have to scroll/filter the big list. Would be nicer if I could just find the building in the main UI (select it's icon) and then click settings 'tab' and have that building automatically selected in the settings screen.

Currently I just plop down a building then open it's info view then click RICO button to get to settings for a building. Would be nice to skip the 'plop and open info view' part of that process.

**Comment by algernon-A** [comment]
Fixed by 3fc543d95327193060d23fb19a882995dd898cc1
281214cc467ac1eb1d9dc3a7f9823b3420067f59 also adds settings panel open on double-click of building button

**Comment by originalfoo** [comment]
Awesome!
