### ISSUE TITLE
how to do select multiple assets and set to RICO?

### ISSUE THREAD

**Issue by linconz** [algernon-A/Ploppable-RICO-Revisited#54]
It's very time consuming that I cannot select multiple assets.
Do you have any plans for implementing this?
Or...can you tell me where is the GUI list source in the code

**Comment by algernon-A** [comment]
I do have plans to do that - although it would help me determine implementation focus if you could tell me exactly what you're trying to do (as in, why do you want to select multiple)?

**Comment by algernon-A** [comment]
Closing this as OP hasn't responded in over two months, and hasn't provided a use case.
