### ISSUE TITLE
Add option to stop style despawning

### ISSUE THREAD

**Issue by algernon-A** [algernon-A/Ploppable-RICO-Revisited#63]
District building styles will despawn plopped growables not of that style.  Need to override this,.

**Comment by algernon-A** [comment]
Check is in `PrivateBuildingAI.SimulationStep`.

**Comment by meda22** [comment]
Hi!
I see that you've added possibility to turn off despawn of growables which are not in style - which is pretty cool option to have. But it seems that check box in settings does not have any effect on functionality - despawning will be always disabled, even if checkbox is not checked. So just a heads up :) 

Just some background - I am trying to create a mod (I call it DistrictStylesPlus) for managing styles during gameplay (so far it basically uses BT UI to handle Styles packages in-game and adding/removing buildings) and just found out this when I was testing with some other mods to see possible issues.

**Comment by algernon-A** [comment]
Retested after report by meda22 of despawning always disabled; unable to reproduce and confirm that functionality WAD.
